version: "3.4"
services:
  facade:
    environment:
      - MONGO_HOST=mongo_db:27017
    build:
      context: ./src/kalytical/facade
  mongo_db:
    image: mongo:3.6
    expose:
      - "27017"
    ports:
      - "27017:27017"