version: "3.4"
services:
  kalytical:
    environment:
      - MONGO_HOST=mongo_db:27017
    build:
      context: ./
      target: deployment
    ports:
      - 8008:8008
  # mongo_db:
  #   image: mongo:3.6
  #   expose:
  #     - "27017"
  #   ports:
  #     - "27017:27017"