version: '3.4'
services:
  kalytical:
    environment:
      - MONGO_HOST=mongo_db:27017
    build:
      context: ./
      target: development
    volumes:
      - .:/workspace:cached
      - C:\Users\brads\.ssh:/root/.ssh/
    command: /bin/sh -c "while sleep 1000; do :; done"
 
